name: MemeScraper

on:
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours (adjust as needed)
  workflow_dispatch:

jobs:
  scrape-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Python packages
        run: |
          pip install snscrape requests

      - name: Fix SSL Certificates
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates
          sudo update-ca-certificates

      - name: Run Meme Scraper
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python meme.py
